// <auto-generated />
namespace ShahidSoltaniLibrary.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class loan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loan));
        
        string IMigrationMetadata.Id
        {
            get { return "202402011502329_loan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
